Footer
PavloOliinyk/project-group7-ice-cream pull request #4
Opened 2021-04-22 21:07 UTC by Rahmanov-Viusal

2021-04-22 21:34 UTC, PavloOliinyk requested changes

2021-04-22 21:34 UTC, PavloOliinyk commented on src/partials/footer.html
> +    <div>
Добавь класс для div`а, например,  footer-title__wrapper

2021-04-22 21:34 UTC, PavloOliinyk commented on src/images/sprite/symbol-defs.svg
> +<path fill="#fff" style="fill: var(--color1, #fff)" d="M17.343 21.048l-0.675 8.86c0.966 0 1.384-0.387 1.885-0.852l4.527-4.038 9.381 6.412c1.72 0.895 2.933 0.424 3.397-1.477l6.159-26.93c0.546-2.374-0.
Убери филы в svg иконках

2021-04-22 21:34 UTC, PavloOliinyk commented on src/partials/footer.html
> +      <h2 class="footer__title title">with passion</h2>
title поставь перед footer__title   Это универсальный класс, он должен быть первым

2021-04-22 21:34 UTC, PavloOliinyk commented on src/sass/layout/_footer.scss
> +  font-style: normal;
Убери font-style везде. Он нужен только в address

2021-04-22 21:34 UTC, PavloOliinyk commented on src/sass/layout/_footer.scss
> +  font-family: DM Sans;
Убери font-family

2021-04-22 21:34 UTC, PavloOliinyk commented on src/sass/layout/_footer.scss
> +  text-align: right;
Убери text-align

2021-04-23 04:09 UTC, Rahmanov-Viusal commented on src/partials/footer.html
> +    <div>
исправил

2021-04-23 04:09 UTC, Rahmanov-Viusal commented on src/images/sprite/symbol-defs.svg
> +<path fill="#fff" style="fill: var(--color1, #fff)" d="M17.343 21.048l-0.675 8.86c0.966 0 1.384-0.387 1.885-0.852l4.527-4.038 9.381 6.412c1.72 0.895 2.933 0.424 3.397-1.477l6.159-26.93c0.546-2.374-0.
исправил

2021-04-23 04:10 UTC, Rahmanov-Viusal commented on src/partials/footer.html
> +      <h2 class="footer__title title">with passion</h2>
исправил

2021-04-23 04:12 UTC, Rahmanov-Viusal commented on src/sass/layout/_footer.scss
> +  font-style: normal;
исправил

2021-04-23 04:14 UTC, Rahmanov-Viusal commented on src/sass/layout/_footer.scss
> +  font-family: DM Sans;
убрал

2021-04-23 04:18 UTC, Rahmanov-Viusal commented on src/sass/layout/_footer.scss
> +  text-align: right;
сделал

2021-04-23 05:55 UTC, PavloOliinyk approved these changes
Исправлено

2021-04-23 05:56 UTC, merged